/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-hero': HomeHero;
    'home-member-spotlight': HomeMemberSpotlight;
    'home-mission': HomeMission;
    'home-partnership': HomePartnership;
    'home-pillars': HomePillar;
    'home-stats': HomeStat;
    'home-upcoming-programs-sections': HomeUpcomingProgramsSection;
    programs: Program;
    stats: Stat;
    'community-member': CommunityMember;
    'about-statistics': AboutStatistic;
    'about-our-story': AboutOurStory;
    'about-founders': AboutFounder;
    'programs-hero': ProgramsHero;
    'programs-section': ProgramsSection;
    'get-involved-hero': GetInvolvedHero;
    'get-involved-opportunities': GetInvolvedOpportunity;
    'partnership-hero': PartnershipHero;
    'partnership-options': PartnershipOption;
    'volunteer-page': VolunteerPage;
    'donate-page': DonatePage;
    'program-details-data': ProgramDetailsDatum;
    'about-hero': AboutHero;
    'about-vision-and-mission': AboutVisionAndMission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-member-spotlight': HomeMemberSpotlightSelect<false> | HomeMemberSpotlightSelect<true>;
    'home-mission': HomeMissionSelect<false> | HomeMissionSelect<true>;
    'home-partnership': HomePartnershipSelect<false> | HomePartnershipSelect<true>;
    'home-pillars': HomePillarsSelect<false> | HomePillarsSelect<true>;
    'home-stats': HomeStatsSelect<false> | HomeStatsSelect<true>;
    'home-upcoming-programs-sections': HomeUpcomingProgramsSectionsSelect<false> | HomeUpcomingProgramsSectionsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'community-member': CommunityMemberSelect<false> | CommunityMemberSelect<true>;
    'about-statistics': AboutStatisticsSelect<false> | AboutStatisticsSelect<true>;
    'about-our-story': AboutOurStorySelect<false> | AboutOurStorySelect<true>;
    'about-founders': AboutFoundersSelect<false> | AboutFoundersSelect<true>;
    'programs-hero': ProgramsHeroSelect<false> | ProgramsHeroSelect<true>;
    'programs-section': ProgramsSectionSelect<false> | ProgramsSectionSelect<true>;
    'get-involved-hero': GetInvolvedHeroSelect<false> | GetInvolvedHeroSelect<true>;
    'get-involved-opportunities': GetInvolvedOpportunitiesSelect<false> | GetInvolvedOpportunitiesSelect<true>;
    'partnership-hero': PartnershipHeroSelect<false> | PartnershipHeroSelect<true>;
    'partnership-options': PartnershipOptionsSelect<false> | PartnershipOptionsSelect<true>;
    'volunteer-page': VolunteerPageSelect<false> | VolunteerPageSelect<true>;
    'donate-page': DonatePageSelect<false> | DonatePageSelect<true>;
    'program-details-data': ProgramDetailsDataSelect<false> | ProgramDetailsDataSelect<true>;
    'about-hero': AboutHeroSelect<false> | AboutHeroSelect<true>;
    'about-vision-and-mission': AboutVisionAndMissionSelect<false> | AboutVisionAndMissionSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: string;
  badge: string;
  title: string;
  subtitle: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  href: string;
  hrefText: string;
  photo: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-member-spotlight".
 */
export interface HomeMemberSpotlight {
  id: string;
  badge: string;
  title: string;
  titleTextToHilight?: string | null;
  description?: string | null;
  titleTwo: string;
  descriptionTwo: string;
  memberToSpotlight: string | CommunityMember;
  members: (string | CommunityMember)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-member".
 */
export interface CommunityMember {
  id: string;
  name?: string | null;
  role?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-mission".
 */
export interface HomeMission {
  id: string;
  badge: string;
  title: string;
  titleTextToHilight?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  href?: string | null;
  hrefText?: string | null;
  stats?:
    | {
        value?: number | null;
        surfix?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partnership".
 */
export interface HomePartnership {
  id: string;
  badge: string;
  title: string;
  titleTextToHilight?: string | null;
  description: string;
  titleTwo: string;
  descriptionTwo: string;
  href: string;
  hrefText: string;
  hrefTwo: string;
  hrefTwoText: string;
  companies: (string | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-pillars".
 */
export interface HomePillar {
  id: string;
  badge: string;
  title: string;
  titleTextToHilight?: string | null;
  description?: string | null;
  pillars?:
    | {
        title: string;
        subtitle: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-stats".
 */
export interface HomeStat {
  id: string;
  badge?: string | null;
  title?: string | null;
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  href?: string | null;
  hrefText?: string | null;
  stats: (string | Stat)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: string;
  title: string;
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-upcoming-programs-sections".
 */
export interface HomeUpcomingProgramsSection {
  id: string;
  badge: string;
  title: string;
  titleTextToHilight?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: string;
  badge: string;
  cohort: string;
  title: string;
  href: string;
  hrefText: string;
  startDate: string;
  location: string;
  email: string;
  phone: string;
  ctaText: string;
  problemStatement: string;
  description: string;
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tracks?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        id?: string | null;
      }[]
    | null;
  thumbnail: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-statistics".
 */
export interface AboutStatistic {
  id: string;
  title: string;
  subtitle: string;
  metrics?:
    | {
        value: number;
        label: string;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-our-story".
 */
export interface AboutOurStory {
  id: string;
  title: string;
  timelineItems?:
    | {
        year: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-founders".
 */
export interface AboutFounder {
  id: string;
  title: string;
  subtitle: string;
  founders?:
    | {
        name: string;
        role: string;
        workTitle: string;
        bio: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        linkedin?: string | null;
        photo: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-hero".
 */
export interface ProgramsHero {
  id: string;
  badge: string;
  title: string;
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-section".
 */
export interface ProgramsSection {
  id: string;
  badge: string;
  title: string;
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-hero".
 */
export interface GetInvolvedHero {
  id: string;
  badge: string;
  title: string;
  subtitle: string;
  href?: string | null;
  hrefText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-opportunities".
 */
export interface GetInvolvedOpportunity {
  id: string;
  title: string;
  subtitle: string;
  opportunities?:
    | {
        title: string;
        subtitle: string;
        description: string;
        iconName: string;
        link: string;
        linkText: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-hero".
 */
export interface PartnershipHero {
  id: string;
  badge: string;
  title: string;
  subtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-options".
 */
export interface PartnershipOption {
  id: string;
  title: string;
  subtitle: string;
  options?:
    | {
        title: string;
        description: string;
        benefits?:
          | {
              benefit: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  brochureTitle: string;
  brochureDescription: string;
  brochureFile: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page".
 */
export interface VolunteerPage {
  id: string;
  heroBadge: string;
  heroTitle: string;
  heroDescription: string;
  missionTitle: string;
  missionContent: string;
  empowermentTitle: string;
  empowermentContent: string;
  opportunitiesTitle: string;
  opportunitiesContent: string;
  roles?:
    | {
        title: string;
        description: string;
        link: string;
        linkText: string;
        requirements?:
          | {
              requirement: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate-page".
 */
export interface DonatePage {
  id: string;
  badge: string;
  heroTitle: string;
  heroDescription: string;
  impacts?:
    | {
        impact: string;
        id?: string | null;
      }[]
    | null;
  allocationTitle: string;
  allocationItems?:
    | {
        name: string;
        icon: string;
        id?: string | null;
      }[]
    | null;
  methods?:
    | {
        title: string;
        description: string;
        details?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        actionLink?: string | null;
        actionText?: string | null;
        iconType: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-details-data".
 */
export interface ProgramDetailsDatum {
  id: string;
  title: string;
  subtitle: string;
  overview: string;
  problemStatement: string;
  impacts?:
    | {
        impact: string;
        id?: string | null;
      }[]
    | null;
  ctaText: string;
  testimonials?:
    | {
        quote: string;
        author: string;
        id?: string | null;
      }[]
    | null;
  address: string;
  email: string;
  phone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero".
 */
export interface AboutHero {
  id: string;
  badge: string;
  title: string;
  subtitle: string;
  href: string;
  hrefText: string;
  photo: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-vision-and-mission".
 */
export interface AboutVisionAndMission {
  id: string;
  mission: {
    badge: string;
    title: string;
  };
  diversity: {
    title: string;
    description: string;
  };
  vision: {
    title: string;
    description: string;
  };
  coreValues: {
    title: string;
    values?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'home-hero';
        value: string | HomeHero;
      } | null)
    | ({
        relationTo: 'home-member-spotlight';
        value: string | HomeMemberSpotlight;
      } | null)
    | ({
        relationTo: 'home-mission';
        value: string | HomeMission;
      } | null)
    | ({
        relationTo: 'home-partnership';
        value: string | HomePartnership;
      } | null)
    | ({
        relationTo: 'home-pillars';
        value: string | HomePillar;
      } | null)
    | ({
        relationTo: 'home-stats';
        value: string | HomeStat;
      } | null)
    | ({
        relationTo: 'home-upcoming-programs-sections';
        value: string | HomeUpcomingProgramsSection;
      } | null)
    | ({
        relationTo: 'programs';
        value: string | Program;
      } | null)
    | ({
        relationTo: 'stats';
        value: string | Stat;
      } | null)
    | ({
        relationTo: 'community-member';
        value: string | CommunityMember;
      } | null)
    | ({
        relationTo: 'about-statistics';
        value: string | AboutStatistic;
      } | null)
    | ({
        relationTo: 'about-our-story';
        value: string | AboutOurStory;
      } | null)
    | ({
        relationTo: 'about-founders';
        value: string | AboutFounder;
      } | null)
    | ({
        relationTo: 'programs-hero';
        value: string | ProgramsHero;
      } | null)
    | ({
        relationTo: 'programs-section';
        value: string | ProgramsSection;
      } | null)
    | ({
        relationTo: 'get-involved-hero';
        value: string | GetInvolvedHero;
      } | null)
    | ({
        relationTo: 'get-involved-opportunities';
        value: string | GetInvolvedOpportunity;
      } | null)
    | ({
        relationTo: 'partnership-hero';
        value: string | PartnershipHero;
      } | null)
    | ({
        relationTo: 'partnership-options';
        value: string | PartnershipOption;
      } | null)
    | ({
        relationTo: 'volunteer-page';
        value: string | VolunteerPage;
      } | null)
    | ({
        relationTo: 'donate-page';
        value: string | DonatePage;
      } | null)
    | ({
        relationTo: 'program-details-data';
        value: string | ProgramDetailsDatum;
      } | null)
    | ({
        relationTo: 'about-hero';
        value: string | AboutHero;
      } | null)
    | ({
        relationTo: 'about-vision-and-mission';
        value: string | AboutVisionAndMission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  href?: T;
  hrefText?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-member-spotlight_select".
 */
export interface HomeMemberSpotlightSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleTextToHilight?: T;
  description?: T;
  titleTwo?: T;
  descriptionTwo?: T;
  memberToSpotlight?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-mission_select".
 */
export interface HomeMissionSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleTextToHilight?: T;
  description?: T;
  href?: T;
  hrefText?: T;
  stats?:
    | T
    | {
        value?: T;
        surfix?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partnership_select".
 */
export interface HomePartnershipSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleTextToHilight?: T;
  description?: T;
  titleTwo?: T;
  descriptionTwo?: T;
  href?: T;
  hrefText?: T;
  hrefTwo?: T;
  hrefTwoText?: T;
  companies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-pillars_select".
 */
export interface HomePillarsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleTextToHilight?: T;
  description?: T;
  pillars?:
    | T
    | {
        title?: T;
        subtitle?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-stats_select".
 */
export interface HomeStatsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  href?: T;
  hrefText?: T;
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-upcoming-programs-sections_select".
 */
export interface HomeUpcomingProgramsSectionsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleTextToHilight?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  badge?: T;
  cohort?: T;
  title?: T;
  href?: T;
  hrefText?: T;
  startDate?: T;
  location?: T;
  email?: T;
  phone?: T;
  ctaText?: T;
  problemStatement?: T;
  description?: T;
  fullDescription?: T;
  tracks?:
    | T
    | {
        text?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        id?: T;
      };
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-member_select".
 */
export interface CommunityMemberSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  description?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-statistics_select".
 */
export interface AboutStatisticsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        suffix?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-our-story_select".
 */
export interface AboutOurStorySelect<T extends boolean = true> {
  title?: T;
  timelineItems?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-founders_select".
 */
export interface AboutFoundersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  founders?:
    | T
    | {
        name?: T;
        role?: T;
        workTitle?: T;
        bio?: T;
        linkedin?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-hero_select".
 */
export interface ProgramsHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-section_select".
 */
export interface ProgramsSectionSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-hero_select".
 */
export interface GetInvolvedHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  href?: T;
  hrefText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-opportunities_select".
 */
export interface GetInvolvedOpportunitiesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  opportunities?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        iconName?: T;
        link?: T;
        linkText?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-hero_select".
 */
export interface PartnershipHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-options_select".
 */
export interface PartnershipOptionsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  options?:
    | T
    | {
        title?: T;
        description?: T;
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
        id?: T;
      };
  brochureTitle?: T;
  brochureDescription?: T;
  brochureFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page_select".
 */
export interface VolunteerPageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitle?: T;
  heroDescription?: T;
  missionTitle?: T;
  missionContent?: T;
  empowermentTitle?: T;
  empowermentContent?: T;
  opportunitiesTitle?: T;
  opportunitiesContent?: T;
  roles?:
    | T
    | {
        title?: T;
        description?: T;
        link?: T;
        linkText?: T;
        requirements?:
          | T
          | {
              requirement?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate-page_select".
 */
export interface DonatePageSelect<T extends boolean = true> {
  badge?: T;
  heroTitle?: T;
  heroDescription?: T;
  impacts?:
    | T
    | {
        impact?: T;
        id?: T;
      };
  allocationTitle?: T;
  allocationItems?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  methods?:
    | T
    | {
        title?: T;
        description?: T;
        details?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        actionLink?: T;
        actionText?: T;
        iconType?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-details-data_select".
 */
export interface ProgramDetailsDataSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  overview?: T;
  problemStatement?: T;
  impacts?:
    | T
    | {
        impact?: T;
        id?: T;
      };
  ctaText?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        id?: T;
      };
  address?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero_select".
 */
export interface AboutHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  href?: T;
  hrefText?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-vision-and-mission_select".
 */
export interface AboutVisionAndMissionSelect<T extends boolean = true> {
  mission?:
    | T
    | {
        badge?: T;
        title?: T;
      };
  diversity?:
    | T
    | {
        title?: T;
        description?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        description?: T;
      };
  coreValues?:
    | T
    | {
        title?: T;
        values?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}